language: php

php:
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
    - gem install sass
    - npm install gulp
    - npm install bower

script:
  - make production
